<!doctype html>
<html lang="pt_BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>K13</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous">
    </script>
    <style>
        .error {
            color: #bd2130;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-8 mx-auto h-100 card mt-5">
            <?= content($viewName, $vars) ?>
        </div>
    </div>
</div>
</body>
</html>