<div class="card-header">
    <h5><?= $user->name ?></h5>
</div>
<div class="card-body">
    <div class="row">
        <div class="col-4 text-right font-weight-bold">
            CEP:
        </div>
        <div class="col-8">
            <?= $user->cep ?>
        </div>
        <div class="col-4 text-right font-weight-bold">
            Rua:
        </div>
        <div class="col-8">
            <?= $user->road ?>
        </div>
        <div class="col-4 text-right font-weight-bold">
            Número:
        </div>
        <div class="col-8">
            <?= $user->number ?>
        </div>
        <div class="col-4 text-right font-weight-bold">
            Complemento:
        </div>
        <div class="col-8">
            <?= $user->complement ?>
        </div>
        <div class="col-4 text-right font-weight-bold">
            Bairro:
        </div>
        <div class="col-8">
            <?= $user->neigh ?>
        </div>
        <div class="col-4 text-right font-weight-bold">
            Cidade:
        </div>
        <div class="col-8">
            <?= $user->city ?>
        </div>
        <div class="col-4 text-right font-weight-bold">
            Estado:
        </div>
        <div class="col-8">
            <?= $user->state ?>
        </div>
    </div>
    <?php if($user->phones()): ?>
        <hr>
        <div class="row">
        <?php $i = 1; foreach ($user->phones() as $phone): ?>
        <div class="col-sm-4 text-right font-weight-bold">
            Telefone <?= $i ?>:
        </div>
       <div class="col-sm-8">
            <span class="phone-number"><?= $phone->number ?></span>
       </div>
        <?php $i++; endforeach; ?>
    </div>
    <?php endif; ?>
</div>
<div class="card-footer">
    <div class="float-left">
        <a href="/" class="btn btn-primary">Voltar à lista</a>
    </div>
    <div class="float-right">
        <a href="/edit/<?= $user->id ?>" class="btn btn-warning">Editar</a>
        <a href="/delete/<?= $user->id ?>" class="btn btn-danger">Deletar</a>
    </div>
</div>

<script type="text/javascript" src="/js/jquery.mask.js"></script>
<script>
    var PhoneMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        PhoneOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(PhoneMaskBehavior.apply({}, arguments), options);
            }
        };
    $('.phone-number').mask(PhoneMaskBehavior, PhoneOptions);

</script>